routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\FeatureController;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\PricingController;
use App\Http\Controllers\PrivillegeController;
use App\Http\Controllers\ReadUpdateController;
use App\Http\Middleware\AlreadyLogin;
use App\Http\Middleware\Guest;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [IndexController::class, 'index'])->name('dashboard');

Route::middleware([Guest::class])->group(function () {

    Route::get('/register', [AdminController::class, 'register'])->name('/register');
    Route::post('/register/store', [AdminController::class, 'store'])->name('/register/store');
    Route::get('/login', [AdminController::class, 'login'])->name('/login');
    Route::post('/login/action', [AdminController::class, 'action'])->name('/login/action');

});

Route::middleware([AlreadyLogin::class])->group(function () {

    Route::get('/admin', [AdminController::class, 'main'])->name('/admin');
    Route::get('/profile', [AdminController::class, 'profile'])->name('/profile');
    Route::post('/profile/update', [AdminController::class, 'update'])->name('/profile/update');

    Route::group(['prefix' => 'feature', 'as' => 'feature.'], function () {
        Route::get('/', [FeatureController::class, 'feature'])->name('feature');
        Route::get('/add', [FeatureController::class, 'add'])->name('add');
        Route::post('/store', [FeatureController::class, 'store'])->name('store');
        Route::get('/edit/{feature}', [FeatureController::class, 'edit'])->name('edit');
        Route::post('/update/{feature}', [FeatureController::class, 'update'])->name('update');
        Route::get('/delete/{feature}', [FeatureController::class, 'delete'])->name('delete');
    });

    Route::group(['prefix' => 'pricing', 'as' => 'pricing.'], function () {
        Route::get('/', [PricingController::class, 'pricing'])->name('pricing');
        Route::get('/add', [PricingController::class, 'add'])->name('add');
        
        Route::post('/store', [PricingController::class, 'store'])->name('store');
        Route::get('/edit/{pricing}', [PricingController::class, 'edit'])->name('edit');
        Route::post('/update/{pricing}', [PricingController::class, 'update'])->name('update');
        Route::get('/delete/{pricing}', [PricingController::class, 'delete'])->name('delete');
    });
        Route::get('/privillege', [PrivillegeController::class, 'privillege'])->name('privillege');
        Route::get('/addPrivillege/{id_pricing}', [PricingController::class, 'addPrivillege'])->name('addPrivillege/{id_pricing}');
        Route::get('/editPrivillege/{id}', [PrivillegeController::class, 'editPrivillege'])->name('editPrivillege/{id}');
        Route::post('/storePrivillege', [PricingController::class, 'storePrivillege'])->name('storePrivillege');
        Route::post('/updatePrivillege/{id}', [PrivillegeController::class, 'updatePrivillege'])->name('updatePrivillege/{id}');
        Route::get('/delete/{id}', [PrivillegeController::class, 'delete'])->name('delete/{id}');

    Route::group(['prefix' => 'info', 'as' => 'info.'], function () {
        Route::get('/', [ReadUpdateController::class, 'coba'])->name('info');
        Route::get('/edit/{info}', [ReadUpdateController::class, 'editInfo'])->name('edit');
        Route::post('/update/{info}', [ReadUpdateController::class, 'updateInfo'])->name('update');
    });

    Route::group(['prefix' => 'contact', 'as' => 'contact.'], function () {
        Route::get('/', [ReadUpdateController::class, 'contact'])->name('contact');
        Route::get('/edit/{contact}', [ReadUpdateController::class, 'editContact'])->name('edit');
        Route::post('/update/{contact}', [ReadUpdateController::class, 'updateContact'])->name('update');
    });
});

route::get('/logout', [AdminController::class, 'logout']);

app/Models/pricing.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class pricing extends Model
{
    use HasFactory;

    protected $table = 'pricing';
    protected $primaryKey = 'id_pricing';
    public $incrementing = false;
    protected $keyType = 'string';
    protected $guarded = [];

    public function privillege() {
        return $this->HasMany(privillege::class, 'id_pricing', 'id_pricing');
    }
}

app/Http/Controllers/PricingController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\pricing;
use App\Models\privillege;
use Illuminate\Http\Request;

class PricingController extends Controller
{
    public function pricing()
    {
        $pricing = pricing::get();
        return view('admin.pricing.index', compact('pricing'));
    }

    public function add()
    {
        $pricing = null;
        return view("admin.pricing.action", compact('pricing'));
    }

    public function edit(pricing $pricing)
    {
        $pricing = $pricing;
        return view("admin.pricing.action", compact('pricing'));
    }

    public function addPrivillege($id_pricing)
    {
        $pricing = pricing::find($id_pricing);
        return view("admin.pricing.addPrivillege", compact('pricing'));
    }

    public function storePrivillege( Request $request)
    {
        // $request->validate([
        //     'id_pricing' => 'required|unique:pricing,id_pricing',
        //     'categories' => 'required',
        //     'price' => 'required',
        //     'feature' => 'required',
        // ], [
        //     'id_pricing.required' => 'ID pricing harus diisi.',
        //     'id_pricing.unique' => 'ID pricing has been used.',
        //     'categories.required' => 'Judul pricing harus diisi.',
        //     'price.required' => 'Informasi pricing harus diisi.',
        //     'feature.required' => 'Feature pricing harus diisi.',
        // ]);

        privillege::create([
            'id_pricing' => $request->id_pricing,
            'privillege' => $request->privillege
        ]);

        // return redirect()->route('pricing.pricing');
        // Dalam kontroler Anda
        return redirect()->route('pricing.pricing')->with('success', 'Data berhasil ditambahkan!');

    }

    public function store(Request $request)
    {
        $request->validate([
            'id_pricing' => 'required|unique:pricing,id_pricing',
            'categories' => 'required',
            'price' => 'required',
        ], [
            'id_pricing.required' => 'ID pricing harus diisi.',
            'id_pricing.unique' => 'ID pricing has been used.',
            'categories.required' => 'Judul pricing harus diisi.',
            'price.required' => 'Informasi pricing harus diisi.',
        ]);

        pricing::create([
            'id_pricing' => $request->id_pricing,
            'categories' => $request->categories,
            'price' => $request->price,
        ]);

        // return redirect()->route('pricing.pricing');
        // Dalam kontroler Anda
        return redirect()->route('pricing.pricing')->with('success', 'Data berhasil ditambahkan!');

    }

    public function update(Request $request, pricing $pricing)
    {
        $request->validate([
            'id_pricing' => 'required',
            'categories' => 'required',
            'price' => 'required',
        ], [
            'id_pricing.required' => 'ID pricing harus diisi.',
            'categories.required' => 'Judul pricing harus diisi.',
            'price.required' => 'Informasi pricing harus diisi.',
        ]);

        $pricing->update([
            'id_pricing' => $request->id_pricing,
            'categories' => $request->categories,
            'price' => $request->price,
        ]);

        // return redirect()->route('pricing.pricing');
        return redirect()->route('pricing.pricing')->with('success', 'Data berhasil diubah!');

    }

    public function delete (pricing $pricing)
    {
            // $pricing parameter sudah berisi instansiasi snackbox berdasarkan id_pricing
    
        if (!$pricing) {
            // Jika pricing tidak ditemukan, mungkin hendak menampilkan pesan error atau melakukan tindakan lain
            return redirect('/pricing')->with('error', 'pricing not found');
        }
    
        // Hapus record pricing dari database
        $pricing->delete();
    
        // Redirect ke halaman yang sesuai atau tampilkan pesan sukses
        return redirect('/pricing')->with('success', 'pricing deleted successfully');
    }
}

resources/views/admin/pricing/action.blade.php
<!DOCTYPE html>
<html lang="en">

@include('admin.layouts.head')

<body>
    <div class="container-scroller">
        <!-- partial:../../partials/_navbar.html -->
        @include('admin.layouts.navbar')
        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
            <!-- partial:../../partials/_settings-panel.html -->
            <div class="theme-setting-wrapper">
                <div id="settings-trigger"><i class="ti-settings"></i></div>
                <div id="theme-settings" class="settings-panel">
                    <i class="settings-close ti-close"></i>
                    <p class="settings-heading">SIDEBAR SKINS</p>
                    <div class="sidebar-bg-options selected" id="sidebar-light-theme">
                        <div class="img-ss rounded-circle bg-light border me-3"></div>Light
                    </div>
                    <div class="sidebar-bg-options" id="sidebar-dark-theme">
                        <div class="img-ss rounded-circle bg-dark border me-3"></div>Dark
                    </div>
                    <p class="settings-heading mt-2">HEADER SKINS</p>
                    <div class="color-tiles mx-0 px-4">
                        <div class="tiles success"></div>
                        <div class="tiles warning"></div>
                        <div class="tiles danger"></div>
                        <div class="tiles info"></div>
                        <div class="tiles dark"></div>
                        <div class="tiles default"></div>
                    </div>
                </div>
            </div>
            
            <!-- partial -->
            <!-- partial:../../partials/_sidebar.html -->
            @include('admin.layouts.sidebar')
            <!-- partial -->
            <div class="main-panel">
                <div class="content-wrapper">
                    <div class="row">
                        <div class="col-md-11 grid-margin stretch-card">
                            <div class="card">
                                <div class="card-body">
                                    <h3 class="card-title">Form Data Pricing</h3>
                                    <form method="post"
                                        action="{{ $pricing ? route('pricing.update', $pricing->id_pricing) : route('pricing.store') }}"
                                        enctype="multipart/form-data" class="forms-sample">
                                        {{ csrf_field() }}

                                        <div class="form-group">
                                            <label for="exampleInputUsername1">ID pricing</label>
                                            <input type="text" class="form-control" id="exampleInputUsername1" name="id_pricing"
                                                placeholder="ID pricing" value="{{ $pricing ? $pricing->id_pricing : old('id_pricing') }}">
                                            @if ($errors->has('id_pricing'))
                                                <div class="text-danger">
                                                    {{ $errors->first('id_pricing') }}
                                                </div>
                                            @endif
                                        </div>

                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Kategori Pricing</label>
                                            <input type="text" class="form-control" id="exampleInputEmail1" name="categories"
                                                placeholder="Kategori Pricing" value="{{ $pricing ? $pricing->categories : old('categories') }}">
                                            @if ($errors->has('categories'))
                                                <div class="text-danger">
                                                    {{ $errors->first('categories') }}
                                                </div>
                                            @endif
                                        </div>

                                        <div class="form-group">
                                            <label for="exampleInputPassword1">Harga</label>
                                            <input type="text" class="form-control" id="exampleInputPassword1" name="price"
                                                placeholder="Harga" value="{{ $pricing ? $pricing->price : old('price') }}">
                                            @if ($errors->has('price'))
                                                <div class="text-danger">
                                                    {{ $errors->first('price') }}
                                                </div>
                                            @endif
                                        </div>

                                        <button type="submit" class="btn btn-primary me-2">Submit</button>
                                        <button class="btn btn-light">Cancel</button>
                                    </form>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
                <!-- content-wrapper ends -->
                <!-- partial:../../partials/_footer.html -->
                @include('admin.layouts.footer')
                <!-- partial -->
            </div>
            <!-- main-panel ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    @include('admin.layouts.script')
</body>

</html>

resources/views/admin/pricing/addPrivillege.blade.php
<!DOCTYPE html>
<html lang="en">

@include('admin.layouts.head')

<body>
    <div class="container-scroller">
        <!-- partial:../../partials/_navbar.html -->
        @include('admin.layouts.navbar')
        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
            <!-- partial:../../partials/_settings-panel.html -->
            <div class="theme-setting-wrapper">
                <div id="settings-trigger"><i class="ti-settings"></i></div>
                <div id="theme-settings" class="settings-panel">
                    <i class="settings-close ti-close"></i>
                    <p class="settings-heading">SIDEBAR SKINS</p>
                    <div class="sidebar-bg-options selected" id="sidebar-light-theme">
                        <div class="img-ss rounded-circle bg-light border me-3"></div>Light
                    </div>
                    <div class="sidebar-bg-options" id="sidebar-dark-theme">
                        <div class="img-ss rounded-circle bg-dark border me-3"></div>Dark
                    </div>
                    <p class="settings-heading mt-2">HEADER SKINS</p>
                    <div class="color-tiles mx-0 px-4">
                        <div class="tiles success"></div>
                        <div class="tiles warning"></div>
                        <div class="tiles danger"></div>
                        <div class="tiles info"></div>
                        <div class="tiles dark"></div>
                        <div class="tiles default"></div>
                    </div>
                </div>
            </div>
            
            <!-- partial -->
            <!-- partial:../../partials/_sidebar.html -->
            @include('admin.layouts.sidebar')
            <!-- partial -->
            <div class="main-panel">
                <div class="content-wrapper">
                    <div class="row">
                        <div class="col-md-11 grid-margin stretch-card">
                            <div class="card">
                                <div class="card-body">
                                    <h3 class="card-title">Form Data Privillege </h3>
                                    <form method="post"
                                        action="/storePrivillege"
                                        enctype="multipart/form-data" class="forms-sample">
                                        {{ csrf_field() }}

                                        <div class="form-group">
                                            <label for="exampleInputUsername1">ID pricing</label>
                                            <input type="text" class="form-control" id="exampleInputUsername1" name="id_pricing"
                                                placeholder="ID pricing" value="{{ $pricing->id_pricing }}">
                                            @if ($errors->has('id_pricing'))
                                                <div class="text-danger">
                                                    {{ $errors->first('id_pricing') }}
                                                </div>
                                            @endif
                                        </div>

                                        <div class="form-group">
                                            <label for="exampleInputPassword1">Privillege Yang Didapat</label>
                                            <input type="text" class="form-control" id="exampleInputPassword1" name="privillege"
                                                placeholder="Fitur Yang Didapat">
                                            @if ($errors->has('privillege'))
                                                <div class="text-danger">
                                                    {{ $errors->first('privillege') }}
                                                </div>
                                            @endif
                                        </div>

                                        <button type="submit" class="btn btn-primary me-2">Submit</button>
                                        <button class="btn btn-light">Cancel</button>
                                    </form>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
                <!-- content-wrapper ends -->
                <!-- partial:../../partials/_footer.html -->
                @include('admin.layouts.footer')
                <!-- partial -->
            </div>
            <!-- main-panel ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    @include('admin.layouts.script')
</body>

</html>

resources/views/admin/pricing/index.blade.php
<!DOCTYPE html>
<html lang="en">

@include('admin.layouts.head')

<body>
  <div class="container-scroller">
    <!-- partial:../../partials/_navbar.html -->
    @include('admin.layouts.navbar')
    <!-- partial -->
    <div class="container-fluid page-body-wrapper">
      <!-- partial:../../partials/_settings-panel.html -->
      <div class="theme-setting-wrapper">
  <div id="settings-trigger"><i class="ti-settings"></i></div>
  <div id="theme-settings" class="settings-panel">
    <i class="settings-close ti-close"></i>
    <p class="settings-heading">SIDEBAR SKINS</p>
    <div class="sidebar-bg-options selected" id="sidebar-light-theme">
      <div class="img-ss rounded-circle bg-light border me-3"></div>Light
    </div>
    <div class="sidebar-bg-options" id="sidebar-dark-theme">
      <div class="img-ss rounded-circle bg-dark border me-3"></div>Dark
    </div>
    <p class="settings-heading mt-2">HEADER SKINS</p>
    <div class="color-tiles mx-0 px-4">
      <div class="tiles success"></div>
      <div class="tiles warning"></div>
      <div class="tiles danger"></div>
      <div class="tiles info"></div>
      <div class="tiles dark"></div>
      <div class="tiles default"></div>
    </div>
  </div>
</div>

      <!-- partial -->
      <!-- partial:../../partials/_sidebar.html -->
      @include('admin.layouts.sidebar')
      <!-- partial -->
      <div class="main-panel">
        <div class="content-wrapper">
          <div class="row">
            
            <div class="col-lg-12 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <div class="card-body d-flex justify-content-between align-items-center">
                    <h4 class="card-title">Data Pricing</h4>
                    <div class="text-right">
                        <a href="{{ route('pricing.add') }}" class="btn btn-primary" data-toggle=""
                            style="border-radius: 7px; margin-left:50px;">
                            <span><i class="fas fa-plus mx-1"></i>  Tambah Fitur</span>
                        </a>
                    </div>
                </div>
                  <div class="table-responsive">
                    <table class="table table-striped">
                      <thead>
                        <tr>
                          <th>
                            ID Pricing
                          </th>
                          <th>
                            Kategori
                          </th>
                          <th>
                            Harga
                          </th>
                          <th>
                            Fitur
                          </th>
                          <th>
                            Action
                          </th>
                        </tr>
                      </thead>
                      <tbody>
                        @foreach ($pricing as $item)
                        <tr>
                          <td>
                            {{$item->id_pricing}}
                          </td>
                          <td>
                            {{$item->categories}}
                          </td>
                          <td>
                            ${{$item->price}}/Month
                          </td>
                          <td>
                            @foreach ($item->privillege as $item)
                            <p style="font-size: 1rem">{{$item->privillege}}</p>
                            @endforeach
                          </td>
                          <td>
                            <a href="addPrivillege/{{ $item->id_pricing }}" class="btn btn-primary" data-toggle=""
                              style="border-radius: 7px;">
                               <span>Add Privillege</span> <!-- Ganti dengan kelas ikon edit yang sesuai -->
                           </a>

                            <a href="{{ route('pricing.edit', $item->id_pricing) }}" class="btn btn-primary" data-toggle=""
                              style="border-radius: 7px;">
                               <span><i class="fas fa-edit"></i></span> <!-- Ganti dengan kelas ikon edit yang sesuai -->
                           </a>
                           
                           <a href="{{ route('pricing.delete', $item->id_pricing) }}" class="btn btn-primary" data-toggle=""
                              style="border-radius: 7px;">
                               <span><i class="fas fa-trash-alt"></i></span> <!-- Ganti dengan kelas ikon hapus yang sesuai -->
                           </a>
                           
                            
                          </td>
                        </tr>  
                        @endforeach
                        
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- content-wrapper ends -->
        <!-- partial:../../partials/_footer.html -->
        @include('admin.layouts.footer')
        <!-- partial -->
      </div>
      <!-- main-panel ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>
  <!-- container-scroller -->
  <!-- plugins:js -->
  @include('admin.layouts.script')
</body>

</html>