routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\FeatureController;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\PricingController;
use App\Http\Controllers\PrivillegeController;
use App\Http\Controllers\ReadUpdateController;
use App\Http\Middleware\AlreadyLogin;
use App\Http\Middleware\Guest;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [IndexController::class, 'index'])->name('dashboard');

Route::middleware([Guest::class])->group(function () {

    Route::get('/register', [AdminController::class, 'register'])->name('/register');
    Route::post('/register/store', [AdminController::class, 'store'])->name('/register/store');
    Route::get('/login', [AdminController::class, 'login'])->name('/login');
    Route::post('/login/action', [AdminController::class, 'action'])->name('/login/action');

});

Route::middleware([AlreadyLogin::class])->group(function () {

    Route::get('/admin', [AdminController::class, 'main'])->name('/admin');
    Route::get('/profile', [AdminController::class, 'profile'])->name('/profile');
    Route::post('/profile/update', [AdminController::class, 'update'])->name('/profile/update');

    Route::group(['prefix' => 'feature', 'as' => 'feature.'], function () {
        Route::get('/', [FeatureController::class, 'feature'])->name('feature');
        Route::get('/add', [FeatureController::class, 'add'])->name('add');
        Route::post('/store', [FeatureController::class, 'store'])->name('store');
        Route::get('/edit/{feature}', [FeatureController::class, 'edit'])->name('edit');
        Route::post('/update/{feature}', [FeatureController::class, 'update'])->name('update');
        Route::get('/delete/{feature}', [FeatureController::class, 'delete'])->name('delete');
    });

    Route::group(['prefix' => 'pricing', 'as' => 'pricing.'], function () {
        Route::get('/', [PricingController::class, 'pricing'])->name('pricing');
        Route::get('/add', [PricingController::class, 'add'])->name('add');
        
        Route::post('/store', [PricingController::class, 'store'])->name('store');
        Route::get('/edit/{pricing}', [PricingController::class, 'edit'])->name('edit');
        Route::post('/update/{pricing}', [PricingController::class, 'update'])->name('update');
        Route::get('/delete/{pricing}', [PricingController::class, 'delete'])->name('delete');
    });
        Route::get('/privillege', [PrivillegeController::class, 'privillege'])->name('privillege');
        Route::get('/addPrivillege/{id_pricing}', [PricingController::class, 'addPrivillege'])->name('addPrivillege/{id_pricing}');
        Route::get('/editPrivillege/{id}', [PrivillegeController::class, 'editPrivillege'])->name('editPrivillege/{id}');
        Route::post('/storePrivillege', [PricingController::class, 'storePrivillege'])->name('storePrivillege');
        Route::post('/updatePrivillege/{id}', [PrivillegeController::class, 'updatePrivillege'])->name('updatePrivillege/{id}');
        Route::get('/delete/{id}', [PrivillegeController::class, 'delete'])->name('delete/{id}');

    Route::group(['prefix' => 'info', 'as' => 'info.'], function () {
        Route::get('/', [ReadUpdateController::class, 'coba'])->name('info');
        Route::get('/edit/{info}', [ReadUpdateController::class, 'editInfo'])->name('edit');
        Route::post('/update/{info}', [ReadUpdateController::class, 'updateInfo'])->name('update');
    });

    Route::group(['prefix' => 'contact', 'as' => 'contact.'], function () {
        Route::get('/', [ReadUpdateController::class, 'contact'])->name('contact');
        Route::get('/edit/{contact}', [ReadUpdateController::class, 'editContact'])->name('edit');
        Route::post('/update/{contact}', [ReadUpdateController::class, 'updateContact'])->name('update');
    });
});

route::get('/logout', [AdminController::class, 'logout']);

app/Models/contact.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class contact extends Model
{
    use HasFactory;
    protected $table = 'contacts';
    protected $primaryKey = 'id_contact';
    public $incrementing = false;
    protected $keyType = 'string';
    protected $guarded = [];
}

resources/views/admin/contact/action.blade.php
<!DOCTYPE html>
<html lang="en">

@include('admin.layouts.head')

<body>
    <div class="container-scroller">
        <!-- partial:../../partials/_navbar.html -->
        @include('admin.layouts.navbar')
        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
            <!-- partial:../../partials/_settings-panel.html -->
            <div class="theme-setting-wrapper">
                <div id="settings-trigger"><i class="ti-settings"></i></div>
                <div id="theme-settings" class="settings-panel">
                    <i class="settings-close ti-close"></i>
                    <p class="settings-heading">SIDEBAR SKINS</p>
                    <div class="sidebar-bg-options selected" id="sidebar-light-theme">
                        <div class="img-ss rounded-circle bg-light border me-3"></div>Light
                    </div>
                    <div class="sidebar-bg-options" id="sidebar-dark-theme">
                        <div class="img-ss rounded-circle bg-dark border me-3"></div>Dark
                    </div>
                    <p class="settings-heading mt-2">HEADER SKINS</p>
                    <div class="color-tiles mx-0 px-4">
                        <div class="tiles success"></div>
                        <div class="tiles warning"></div>
                        <div class="tiles danger"></div>
                        <div class="tiles info"></div>
                        <div class="tiles dark"></div>
                        <div class="tiles default"></div>
                    </div>
                </div>
            </div>
            
            <!-- partial -->
            <!-- partial:../../partials/_sidebar.html -->
            @include('admin.layouts.sidebar')
            <!-- partial -->
            <div class="main-panel">
                <div class="content-wrapper">
                    <div class="row">
                        <div class="col-md-11 grid-margin stretch-card">
                            <div class="card">
                                <div class="card-body">
                                    <h3 class="card-title">Form Data Kontak Perusahaan</h3>
                                    <form method="post" action="{{ route('contact.update' , $contact->id_contact) }}"
                                        enctype="multipart/form-data" class="forms-sample">
                                        {{ csrf_field() }}

                                        <div class="form-group">
                                            {{-- <label for="exampleInputUsername1">ID Kontak</label> --}}
                                            <input type="text" class="form-control" id="exampleInputUsername1" name="id_contact"
                                                placeholder="ID Kontak" value="{{ $contact->id_contact}}" hidden>
                                            @if ($errors->has('id_contact'))
                                                <div class="text-danger">
                                                    {{ $errors->first('id_contact') }}
                                                </div>
                                            @endif
                                        </div>

                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Jenis Kontak</label>
                                            <input type="text" class="form-control" id="exampleInputEmail1" name="contact_cat"
                                                placeholder="Jenis Kontak" value="{{ $contact->contact_cat }}">
                                            @if ($errors->has('contact_cat'))
                                                <div class="text-danger">
                                                    {{ $errors->first('contact_cat') }}
                                                </div>
                                            @endif
                                        </div>

                                        <div class="form-group">
                                            <label for="exampleInputPassword1">Informasi</label>
                                            <input type="text" class="form-control" id="exampleInputPassword1" name="information"
                                                placeholder="Informasi" value="{{ $contact->information }}">
                                            @if ($errors->has('information'))
                                                <div class="text-danger">
                                                    {{ $errors->first('information') }}
                                                </div>
                                            @endif
                                        </div>
                                        <button type="submit" class="btn btn-primary me-2">Submit</button>
                                        <button class="btn btn-light">Cancel</button>
                                    </form>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
                <!-- content-wrapper ends -->
                <!-- partial:../../partials/_footer.html -->
                @include('admin.layouts.footer')
                <!-- partial -->
            </div>
            <!-- main-panel ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    @include('admin.layouts.script')
</body>

</html>

resources/views/admin/contact/index.blade.php
<!DOCTYPE html>
<html lang="en">

@include('admin.layouts.head')

<body>
  <div class="container-scroller">
    <!-- partial:../../partials/_navbar.html -->
    @include('admin.layouts.navbar')
    <!-- partial -->
    <div class="container-fluid page-body-wrapper">
      <!-- partial:../../partials/_settings-panel.html -->
      <div class="theme-setting-wrapper">
  <div id="settings-trigger"><i class="ti-settings"></i></div>
  <div id="theme-settings" class="settings-panel">
    <i class="settings-close ti-close"></i>
    <p class="settings-heading">SIDEBAR SKINS</p>
    <div class="sidebar-bg-options selected" id="sidebar-light-theme">
      <div class="img-ss rounded-circle bg-light border me-3"></div>Light
    </div>
    <div class="sidebar-bg-options" id="sidebar-dark-theme">
      <div class="img-ss rounded-circle bg-dark border me-3"></div>Dark
    </div>
    <p class="settings-heading mt-2">HEADER SKINS</p>
    <div class="color-tiles mx-0 px-4">
      <div class="tiles success"></div>
      <div class="tiles warning"></div>
      <div class="tiles danger"></div>
      <div class="tiles info"></div>
      <div class="tiles dark"></div>
      <div class="tiles default"></div>
    </div>
  </div>
</div>

      <!-- partial -->
      <!-- partial:../../partials/_sidebar.html -->
      @include('admin.layouts.sidebar')
      <!-- partial -->
      <div class="main-panel">
        <div class="content-wrapper">
          <div class="row">
            
            <div class="col-lg-12 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <h3 class="card-title">Kontak Perusahaan</h3>
                  <div class="table-responsive">
                    <table class="table table-striped">
                      <thead>
                        <tr>
                          {{-- <th>
                            ID Kontak
                          </th> --}}
                          <th>
                            Kategori Kontak
                          </th>
                          <th>
                            Informasi
                          </th>
                          <th>
                            Action
                          </th>
                        </tr>
                      </thead>
                      <tbody>
                        @foreach ($contact as $item)
                        <tr>
                          {{-- <td>
                            {{$item->id_contact}}
                          </td> --}}
                          <td>
                            {{$item->contact_cat}}
                          </td>
                          <td>
                            {{$item->information}}
                          </td>
                          <td>
                            <a href="{{ route('contact.edit' , $item->id_contact) }}" class="btn btn-primary" data-toggle=""
                              style="border-radius: 7px;">
                              <span><i class="fas fa-edit"></i></span>
                            </a>
                          </td>
                        </tr> 
                        @endforeach
                        
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- content-wrapper ends -->
        <!-- partial:../../partials/_footer.html -->
        @include('admin.layouts.footer')
        <!-- partial -->
      </div>
      <!-- main-panel ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>
  <!-- container-scroller -->
  <!-- plugins:js -->
  @include('admin.layouts.script')
</body>

</html>